name: Imprimir Segredo

on:
  push:
    branches:
      - main

jobs:
  imprimir-segredo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Imprimir Segredo
        run: |
          echo "O valor do meu segredo é ${{ secrets.DEPLOY_PRIVATE_KEY   }}"
